// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkyeP8VroHySEcTMm1pcrRACV49ju7lx0',
    authDomain: 'wildx-6d2ef.firebaseapp.com',
    projectId: 'wildx-6d2ef',
    storageBucket: 'wildx-6d2ef.firebasestorage.app',
    messagingSenderId: '705159796565',
    appId: '1:705159796565:web:f016b47668adc22dfbc1dc',
    measurementId: 'G-16ZLFS8XBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHkkgpBcoX_5CEEt6Nnh0xieznBWrRYI0',
    appId: '1:705159796565:android:8bf86690bb1819bdfbc1dc',
    messagingSenderId: '705159796565',
    projectId: 'wildx-6d2ef',
    storageBucket: 'wildx-6d2ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkyeP8VroHySEcTMm1pcrRACV49ju7lx0',
    appId: '1:705159796565:ios:f016b47668adc22dfbc1dc',
    messagingSenderId: '705159796565',
    projectId: 'wildx-6d2ef',
    storageBucket: 'wildx-6d2ef.firebasestorage.app',
    iosBundleId: 'com.wildx.wildxLogin',
  );
}